// Blog manifest: list post slugs, newest first. Each slug maps to posts/<slug>.md
window.FA_POST_SLUGS = [
  "how-many-answers-has-anyone-read",
  "which-agents-would-fail-an-eu-ai-act-audit",
  "regression-from-trace",
  "guardrail-audit-closed",
  "prove-the-control-was-operating",
  "evidence-not-attestation",
  "eval-invalid-not-green",
  "guardrails-at-every-checkpoint",
  "guardrails-block-before-the-provider",
  "where-should-ai-actually-be",
  "five-people-evaluating-your-agent-platform",
  "guardrails-that-actually-block",
  "agent-framework-is-not-a-harness",
  "strong-model-reads-balance-sheet-wrong",
  "give-your-agent-memory",
  "ship-an-agent-without-evals",
  "your-agent-shouldnt-decide-alone",
  "agent-was-right-data-was-wrong",
  "see-everything-your-agent-does",
  "your-agent-needs-transactions",
  "prompt-changed-agent-broke-nobody-noticed",
  "every-production-failure-becomes-a-test",
  "done-complaining-heres-what-im-shipping"
];
