// Generated by tools/build-blog-meta.js — do not edit by hand.
window.FA_SERIES = {
  "The Evaluation Series": [
    {
      "slug": "evaluation-part-1-before-it-ships",
      "title": "A Prompt Change Is About to Ship. Should It?",
      "part": 1,
      "of": 3
    },
    {
      "slug": "evaluation-part-2-after-it-ships",
      "title": "Tests Passed. Production Is Different.",
      "part": 2,
      "of": 3
    }
  ],
  "The Agent Debugging Manifesto": [
    {
      "slug": "every-production-failure-becomes-a-test",
      "title": "Every Production Failure Should Become a Test. One Click.",
      "part": 1,
      "of": 11
    },
    {
      "slug": "prompt-changed-agent-broke-nobody-noticed",
      "title": "The Prompt Changed. The Agent Broke. Nobody Noticed for 3 Days.",
      "part": 2,
      "of": 11
    },
    {
      "slug": "your-agent-needs-transactions",
      "title": "Your Agent Needs Transactions, Not Just Tools",
      "part": 3,
      "of": 11
    },
    {
      "slug": "see-everything-your-agent-does",
      "title": "I See Everything My Agent Does. In My Own Environment. No Cloud Account.",
      "part": 4,
      "of": 11
    },
    {
      "slug": "agent-was-right-data-was-wrong",
      "title": "The Agent Was Right. The Data Was Wrong.",
      "part": 5,
      "of": 11
    },
    {
      "slug": "your-agent-shouldnt-decide-alone",
      "title": "Your Agent Shouldn't Decide Alone. Here's How to Keep a Human in Command.",
      "part": 6,
      "of": 11
    },
    {
      "slug": "ship-an-agent-without-evals",
      "title": "You Wouldn't Ship Code Without Tests. Why Ship an Agent Without Evals?",
      "part": 7,
      "of": 11
    },
    {
      "slug": "give-your-agent-memory",
      "title": "Give Your Agent Memory It Won't Lie to You",
      "part": 8,
      "of": 11
    },
    {
      "slug": "strong-model-reads-balance-sheet-wrong",
      "title": "Your Strong Model Still Reads a Balance Sheet Wrong",
      "part": 9,
      "of": 11
    },
    {
      "slug": "agent-framework-is-not-a-harness",
      "title": "An Agent Framework Is Not an Agent Harness",
      "part": 10,
      "of": 11
    },
    {
      "slug": "guardrails-that-actually-block",
      "title": "Guardrails That Actually Block",
      "part": 11,
      "of": 11
    }
  ]
};
