// Generated by tools/build-blog-meta.js — do not edit by hand.
window.FA_SERIES = {
  "The Agent Debugging Manifesto": [
    {
      "slug": "every-production-failure-becomes-a-test",
      "title": "Every Production Failure Should Become a Test. One Click.",
      "part": 1
    },
    {
      "slug": "prompt-changed-agent-broke-nobody-noticed",
      "title": "The Prompt Changed. The Agent Broke. Nobody Noticed for 3 Days.",
      "part": 2
    },
    {
      "slug": "your-agent-needs-transactions",
      "title": "Your Agent Needs Transactions, Not Just Tools",
      "part": 3
    },
    {
      "slug": "see-everything-your-agent-does",
      "title": "I See Everything My Agent Does. In My Own Environment. No Cloud Account.",
      "part": 4
    }
  ]
};
